fix: __atomic_always_lock_free() not a constant expression on g++ < 5.1
Building with GCC < 5.1 fails with this kind of error:

  ../include/urcu/compiler.h:60:21: error: expression in static assertion is not constant
    urcu_static_assert(__atomic_always_lock_free(size, 0),

It turns out that prior to GCC 5.1 the builtin
__atomic_always_lock_free() does not evaluate to a constant expression
even if it is documented as such.

To keep support for those older compilers, skip the check and hope for
the best.

Change-Id: I09ea896ccc8fada189ec8ad5c1d32eb855ce6a6f
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>